# Generated by Django 4.1.4 on 2022-12-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_movie_ivdeos_movie_vdeos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='vdeos',
            new_name='videos',
        ),
    ]
